language: ruby
cache: bundler

before_install:
  - gem update bundler

rvm:
  - "2.0.0"
  - "2.1.10"
  - "2.2.10"
  - "2.3.8"
  - "2.4.5"
  - "2.5.3"

matrix:
  exclude:
    - rvm: "2.0.0"
      env: ACTIVESUPPORT_VERSION=5
    - rvm: "2.1.10"
      env: ACTIVESUPPORT_VERSION=5

env:
  - ACTIVESUPPORT_VERSION=3
  - ACTIVESUPPORT_VERSION=4
  - ACTIVESUPPORT_VERSION=5

script:
  - bundle exec rspec ./spec
