language: ruby
cache: bundler

before_install:
  - gem update bundler

rvm:
  - "2.0.0"
  - "2.1.5"
  - "2.2.2"
  - "2.3.0"

matrix:
  exclude:
    - rvm: "2.0.0"
      env: ACTIVESUPPORT_VERSION=5
    - rvm: "2.1.5"
      env: ACTIVESUPPORT_VERSION=5

env:
  - ACTIVESUPPORT_VERSION=3
  - ACTIVESUPPORT_VERSION=4
  - ACTIVESUPPORT_VERSION=5

script:
  - bundle exec rspec ./spec
